In [32]:
import numpy as np

# part (a)

In [39]:
def lu_decomposition(a):
    """
    Iteratively performs LU decomposition (a = L*U)
    L = lower triangular matrix
    U = upper triangular matrix
    """
    a = np.asarray(a, dtype=float)
    
    if a.ndim != 2:
        raise ValueError(f"matrix must be 2-dimensional. Got {a.ndim} dimensions")
    
    if a.shape[0] != a.shape[1]:
        raise ValueError(f"dimension mismatch: " + \
                         f"got matrix with shape {a.shape}")
        
    n = a.shape[0]  # number of dimensions
    
    lt_mtx = np.eye(n)  # initialize lower triangle matrix
    ut_mtx = a.copy()  # initialize upper triangle matrix
    
    for i in range(n):
        # construct L[i]:
        L_i = np.eye(n)
        if i + 1 < n:
            L_i[i+1:, i] = -ut_mtx[i+1:, i]/ut_mtx[i, i]
        
        # carry over to next step
        lt_mtx = lt_mtx @ np.linalg.inv(L_i)
        ut_mtx = L_i @ ut_mtx
        
    return lt_mtx, ut_mtx

In [41]:
def back_substitution(U, y):
    """
    solves the system U*x = y using back substitution
    """
    n = U.shape[0]
    x = np.empty_like(y, dtype=float)
    for i in reversed(range(n)):  # i = n, n-1, n-2, ..., 0
        x[i] = y[i]
        for j in range(i+1, n):  # j = i, i+1, i+2, ..., n
            x[i] -= U[i, j]*x[j]
        x[i] /= U[i, i]
    return x

In [48]:
def forward_substitution(L, b):
    """
    solves the system L*y = b using forward substitution
    """
    n = L.shape[0]
    y = np.empty_like(b, dtype=float)
    for i in range(n):
        y[i] = b[i]
        for j in range(i):
            y[i] -= L[i, j]*y[j]
        y[i] /= L[i, i]
    return y

In [49]:
def solve(a, b):
    """
    solves the system a * x = b 
    using LU decomposition
    """
    
    a = np.asarray(a, dtype=float)
    b = np.squeeze(np.asarray(b, dtype=float))
    
    n = a.shape[0]
    
    # error checking:
    if a.ndim != 2:
        raise ValueError(f"'a' must be 2-dimensional. Got {a.ndim} dimensions")
    
    if a.shape[0] != a.shape[1]:
        raise ValueError(f"dimension mismatch: " + \
                         f"got matrix 'a' with shape {a.shape}")
        
    if b.ndim != 1:
        raise ValueError(f"'b' must be 1-dimensional. Got {b.ndim} dimensions")
        
    if b.shape[0] != n:
        raise ValueError(f"dimension mismatch: " + \
                         f"got matrix 'b' with shape {b.shape}. " + \
                         f"Expected {n} dimensions.")
    
    # perform LU decomposition
    L, U = lu_decomposition(a)
    
    # solve Ly = b (forward substitution):
    y = forward_substitution(L, b)
    
    # solve Ux = y (back substitution):
    x = back_substitution(U, y)
    
    return x

In [66]:
a = [[1, 2, 3],
     [4, 10, 6],
     [7, 8, 9]]
b = [5, 2, 2]
l, u = lu_decomposition(a)
l, u

(array([[ 1.,  0.,  0.],
        [ 4.,  1.,  0.],
        [ 7., -3.,  1.]]),
 array([[  1.,   2.,   3.],
        [  0.,   2.,  -6.],
        [  0.,   0., -30.]]))

In [67]:
solve(a, b)

array([-3.1, -0.3,  2.9])

In [68]:
np.linalg.solve(a, b)

array([-3.1, -0.3,  2.9])

# part (b)

In [69]:
a = [[2, 1, 4, 1],
     [3, 4, -1, -1],
     [1, -4, 1, 5],
     [2, -2, 1, 3]]
b = [-4, 3, 9, 7]

In [70]:
solve(a, b)

array([ 2., -1., -2.,  1.])

In [71]:
np.linalg.solve(a, b)

array([ 2., -1., -2.,  1.])

# part (c)